name: taming
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=10.2
  - pytorch=1.8.1
  - torchvision=0.9.1
  - numpy=1.20.3
  - pip:
    - opencv-python==4.1.2.30
    - pytorch-lightning==1.0.8
    - streamlit>=0.73.1